version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
    open-pull-requests-limit: 10
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    ignore:
      - dependency-name: "discord.js"
        versions:
          - "~> 12"
      - dependency-name: "@types/node"
        versions:
          - "~> 14"
